### ISSUE TITLE
please provide an option to disable the default mapping

### ISSUE THREAD

**Issue by skywind3000** [hahdookin/miniterm.vim#1]
The `<leader>tX` have already been defined for tabpage management in my `.vimrc` and I don't want to change my habit.

So please provide me an option to disable the default mapping of this plugin, so I can map them in my way.

**Comment by chrispane11** [comment]
Addressed in a60ac0e. Setting `g:miniterm_dont_map` to `v:true` somewhere in your `.vimrc` should do the trick.

Thank you.
